// components/mind-map/projects.ts
// Your dataset — cleaned + tagged + axis ratings (hidden; only used for placement).

export type ProjectState = "WIP" | "Active" | "Paused" | "Prototype" | "Complete" | "Concept";

export type Project = {
  id: string;
  name: string;
  description: string; // one sentence: why it exists (not a feature list)
  state: ProjectState;
  // axes are 0..100 but NEVER displayed; only used for positioning
  axes: {
    personal_shared: number; // left (personal) -> right (shared)
    play_purpose: number; // bottom (play) -> top (purpose)
  };
  categories: string[]; // for filtering
  tags: string[]; // “annotations” (rendered as editorial separators)
};

export const projects: Project[] = [
  {
    id: "draftline",
    name: "Draftline",
    description: "Makes iteration visible so writing feels less final.",
    state: "WIP",
    axes: { personal_shared: 40, play_purpose: 85 },
    categories: ["thinking-tools", "writing"],
    tags: ["clarity", "iteration", "systems"],
  },
  {
    id: "patina",
    name: "Patina",
    description: "A small visual playground for texture, imperfection, and mood.",
    state: "Complete",
    axes: { personal_shared: 15, play_purpose: 20 },
    categories: ["creative-play", "visual-experiment"],
    tags: ["texture", "expression", "delight"],
  },
  {
    id: "wander",
    name: "Wander",
    description: "A non-linear interface that encourages curious drifting.",
    state: "WIP",
    axes: { personal_shared: 30, play_purpose: 70 },
    categories: ["thinking-tools", "knowledge"],
    tags: ["curiosity", "connections", "explore"],
  },
  {
    id: "atrophy",
    name: "Atrophy",
    description: "Turns gym attendance into an honest cost-per-session mirror.",
    state: "Prototype",
    axes: { personal_shared: 30, play_purpose: 80 },
    categories: ["behaviour-change", "visualisation", "fitness"],
    tags: ["feedback loops", "self-honesty", "numbers"],
  },
  {
    id: "story-content",
    name: "STORY Content",
    description: "Prompts rough ideas into cleaner narratives and angles.",
    state: "Active",
    axes: { personal_shared: 45, play_purpose: 75 },
    categories: ["thinking-tools", "content"],
    tags: ["storytelling", "structure", "prompts"],
  },
  {
    id: "ripple",
    name: "Ripple",
    description: "An exploration of credit, influence, and where ideas come from.",
    state: "Concept",
    axes: { personal_shared: 70, play_purpose: 80 },
    categories: ["product-shaped", "systems"],
    tags: ["attribution", "networks", "ethics"],
  },
  {
    id: "tendril",
    name: "Tendril",
    description: "Tiny daily prompts to keep skills alive through repetition.",
    state: "Concept",
    axes: { personal_shared: 75, play_purpose: 85 },
    categories: ["education", "learning"],
    tags: ["microlearning", "practice", "memory"],
  },
  {
    id: "receipt-workbench",
    name: "Receipt Workbench",
    description: "A receipt-style way to query personal finance with less friction.",
    state: "WIP",
    axes: { personal_shared: 35, play_purpose: 80 },
    categories: ["thinking-tools", "visualisation"],
    tags: ["finance", "clarity", "interface"],
  },
  {
    id: "covered",
    name: "Covered",
    description: "Fetches posters/cover art so tracking media feels effortless.",
    state: "Complete",
    axes: { personal_shared: 65, play_purpose: 75 },
    categories: ["utility-extension", "media"],
    tags: ["automation", "metadata", "flow"],
  },
  {
    id: "headcount",
    name: "Headcount",
    description: "Uses real crowds to make ‘big numbers’ feel human.",
    state: "Prototype",
    axes: { personal_shared: 45, play_purpose: 30 },
    categories: ["visualisation", "creative-play"],
    tags: ["scale", "perception", "people"],
  },
  {
    id: "gracious",
    name: "Gracious",
    description: "A design-forward storefront experiment in tasteful presentation.",
    state: "Complete",
    axes: { personal_shared: 70, play_purpose: 75 },
    categories: ["product-shaped", "ecommerce"],
    tags: ["shopify", "layout", "brand"],
  },
  {
    id: "ai-chef",
    name: "AI Chef Assistant",
    description: "A playful helper for meal ideas when decision fatigue hits.",
    state: "Prototype",
    axes: { personal_shared: 65, play_purpose: 60 },
    categories: ["product-shaped", "ai"],
    tags: ["food", "assistant", "ideas"],
  },
  {
    id: "c3",
    name: "C3",
    description: "Weekly curiosity-led classes for young builders and thinkers.",
    state: "Active",
    axes: { personal_shared: 85, play_purpose: 90 },
    categories: ["education", "community"],
    tags: ["coding", "science", "warmups"],
  },
  {
    id: "tiktok-tagger",
    name: "TikTok Tagger",
    description: "Captures ‘good’ videos so inspiration doesn’t evaporate.",
    state: "Prototype",
    axes: { personal_shared: 55, play_purpose: 60 },
    categories: ["utility-extension", "social"],
    tags: ["capture", "rediscovery", "workflow"],
  },
  {
    id: "moonstone",
    name: "Moonstone",
    description: "Playlist insights to quickly sense whether a playlist ‘has taste’.",
    state: "Paused",
    axes: { personal_shared: 80, play_purpose: 85 },
    categories: ["product-shaped", "visualisation", "music"],
    tags: ["playlists", "insight", "signal"],
  },
  {
    id: "tactictoe",
    name: "Tactictoe",
    description: "A small game experiment to explore simple AI behaviour.",
    state: "Complete",
    axes: { personal_shared: 40, play_purpose: 25 },
    categories: ["creative-play", "game"],
    tags: ["logic", "rules", "fun"],
  },
  {
    id: "napkin",
    name: "Napkin",
    description: "A fast scratchpad so ideas land somewhere before they drift.",
    state: "WIP",
    axes: { personal_shared: 25, play_purpose: 65 },
    categories: ["thinking-tools"],
    tags: ["notes", "speed", "messy"],
  },
  {
    id: "colour-guesser",
    name: "Colour Guesser",
    description: "A perception toy that rewards intuition over correctness.",
    state: "Complete",
    axes: { personal_shared: 50, play_purpose: 30 },
    categories: ["creative-play", "visual-experiment"],
    tags: ["colour", "game", "delight"],
  },
  {
    id: "speedround",
    name: "Speedround",
    description: "Timeboxed workouts with satisfying progression feedback.",
    state: "Prototype",
    axes: { personal_shared: 30, play_purpose: 75 },
    categories: ["behaviour-change", "fitness"],
    tags: ["timebox", "progress", "push"],
  },
  {
    id: "reel",
    name: "Reel",
    description: "A motion loop experiment — simple, hypnotic, done.",
    state: "Complete",
    axes: { personal_shared: 20, play_purpose: 20 },
    categories: ["creative-play"],
    tags: ["motion", "loops", "visual"],
  },
  {
    id: "c3-curated",
    name: "C3 Curated",
    description: "A rich ‘information diet’ feed for families who want better inputs.",
    state: "WIP",
    axes: { personal_shared: 80, play_purpose: 85 },
    categories: ["education", "content"],
    tags: ["families", "curation", "discovery"],
  },
  {
    id: "order-builder-3d",
    name: "3D Order Builder",
    description: "A highly visual sandbox for rate simulations and order scenarios.",
    state: "Complete",
    axes: { personal_shared: 85, play_purpose: 90 },
    categories: ["visualisation", "work", "tools"],
    tags: ["simulation", "rates", "interaction"],
  },
  {
    id: "asterisk",
    name: "Asterisk",
    description: "Tags design elements with sources so credit stays attached.",
    state: "Prototype",
    axes: { personal_shared: 70, play_purpose: 85 },
    categories: ["utility-extension", "design-tools"],
    tags: ["figma", "attribution", "metadata"],
  },
  {
    id: "little-tap",
    name: "Little Tap",
    description: "NFC touchpoints that make reviews and actions frictionless for customers.",
    state: "WIP",
    axes: { personal_shared: 90, play_purpose: 90 },
    categories: ["product-shaped"],
    tags: ["nfc", "local biz", "growth"],
  },
  {
    id: "c3-sizzle",
    name: "C3 Sizzle",
    description: "A living library of warmups to spark attention before class.",
    state: "WIP",
    axes: { personal_shared: 70, play_purpose: 65 },
    categories: ["education", "creative-play"],
    tags: ["warmups", "engagement", "ideas"],
  },
  {
    id: "excelnt",
    name: "Exceln’t",
    description: "A reimagining of spreadsheets with less cognitive sludge.",
    state: "Concept",
    axes: { personal_shared: 40, play_purpose: 70 },
    categories: ["thinking-tools", "visualisation"],
    tags: ["tables", "friction", "clarity"],
  },
  {
    id: "ember",
    name: "Ember",
    description: "Randomly resurfaces a bookmark so good links don’t die.",
    state: "Complete",
    axes: { personal_shared: 20, play_purpose: 35 },
    categories: ["utility-extension", "creative-play"],
    tags: ["rediscovery", "memory", "tiny"],
  },
  {
    id: "twelve-week-year",
    name: "12 Week Year",
    description: "A cycle-based system for momentum, reflection, and staying honest.",
    state: "Active",
    axes: { personal_shared: 25, play_purpose: 85 },
    categories: ["behaviour-change", "thinking-tools"],
    tags: ["goals", "review", "rhythm"],
  },
  {
    id: "trademe-lock",
    name: "TradeMe Lock",
    description: "Prevents accidental actions so marketplaces feel safer to use.",
    state: "Prototype",
    axes: { personal_shared: 55, play_purpose: 70 },
    categories: ["utility-extension"],
    tags: ["safety", "guardrails", "automation"],
  },
  {
    id: "ascent-lateral-raise-counter",
    name: "Ascent",
    description: "A counter that makes reps feel tangible and slightly addictive.",
    state: "Prototype",
    axes: { personal_shared: 25, play_purpose: 60 },
    categories: ["behaviour-change", "fitness"],
    tags: ["feedback", "reps", "motivation"],
  }
];